In [2]:
# 판다스의 자료구조 : 시리즈, 데이터프레임
import pandas as pd

In [3]:
# 시리즈 생성
sr = pd.Series({'a':1, 'b':2, 'c':3})
print(sr)

print(type(sr))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [4]:
# 시리즈의 인덱스, 값
print(sr.index)
print(sr.values)

Index(['a', 'b', 'c'], dtype='object')
[1 2 3]


In [5]:
# 시리즈를 접근하는 방법 : sr[index], sr[숫자인덱스]
print(sr['a'], sr[0])
print()
print(sr['a':'c'])
print()
print(sr[0:2])

1 1

a    1
b    2
c    3
dtype: int64

a    1
b    2
dtype: int64


In [6]:
# 리스트 또는 튜플을 시리즈로 만들면서 인덱스명 부여
list_data = ['영인', '2000-06-30', '남',True]
sr1 = pd.Series(list_data, index = ['이름','생년월일','성별', '학생여부'])
sr1

이름              영인
생년월일    2000-06-30
성별               남
학생여부          True
dtype: object

In [7]:
sr1[['이름', '생년월일']]

이름              영인
생년월일    2000-06-30
dtype: object

In [8]:
print(sr.dtype)
print(sr1.dtype)
print(type(sr['a']))
print(type(sr1['이름']))

int64
object
<class 'numpy.int64'>
<class 'str'>


In [9]:
# 데이터 프레임 : 시리즈가 여러개 묶여서 됨
# 딕셔너리로 데이터 프레임 생성 -> 키가 컬럼으로 됨
dict_data = {'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]}
df = pd.DataFrame(dict_data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [10]:
print(df.dtypes) # 각 칼럼의 데이터 타입
print(df.index)  # 데이터 프레임의 인덱스 출력
print(df.values) # 각 인덱스의 값 : 2차원 리스트로 출력

a    int64
b    int64
c    int64
dtype: object
RangeIndex(start=0, stop=3, step=1)
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
# 2차원 리스트로 인덱스명과 칼럼명을 부여하면서 데이터 프레임 생성

data = [[15,'남','덕명중'],[17,'여','수리중']]
df = pd.DataFrame(data, index = ['준서', '예은'],
                 columns=['나이','성별','학교'])

df

나이 성별   학교
준서  15  남  덕명중
예은  17  여  수리중

In [12]:
print(df.dtypes) # 각 칼럼의 데이터 타입
print()
print(df.index)  # 데이터 프레임의 인덱스 출력
print()
print(df.columns)
print()
print(df.values) # 각 인덱스의 값 : 2차원 리스트로 출력



나이     int64
성별    object
학교    object
dtype: object

Index(['준서', '예은'], dtype='object')

Index(['나이', '성별', '학교'], dtype='object')

[[15 '남' '덕명중']
 [17 '여' '수리중']]


In [13]:
# 인덱스명을 변경 : 객체.index = [인덱스명.....]       -> 기존 정보수정
# 칼럼명을 변경 : 객체.columns = [칼럼명.....]
# 준서, 예은 -> 학생1,학생2
df.index = ['학생1','학생2']
print(df)
print()
df.columns = ['연령','남녀','소속']
print(df)
print()

     나이 성별   학교
학생1  15  남  덕명중
학생2  17  여  수리중

     연령 남녀   소속
학생1  15  남  덕명중
학생2  17  여  수리중



In [14]:
# 인덱스명과 칼럼명을 일부만 수정하고자 할 경우  -> 기존 정보 수정하고싶으면
# object.rename(index={old:new, .....})               맨뒤에 ,inplace = True
# object.rename(columns={old:new, .....})
# 남녀를 성별로, 학생1을 준서로 수정
df.rename(index = {'학생1,':' 준서'}, columns = {'남녀':'성별'})

연령 성별   소속
학생1  15  남  덕명중
학생2  17  여  수리중

In [15]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

In [17]:
# 서준, 우현, 인아로 인덱스 설정하면서 exam_data를 이용하여 df 생성
df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90